[build]
builder = "NIXPACKS"
buildCommand = "cd server && pip install -r requirements.txt"

[deploy]
startCommand = "cd server && gunicorn run_server:app"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 